main: main.o ft_convert_base.o ft_strcmp.o ft_convert_binary_to_decimal.o ft_convert_binary_to_hexadecimal.o ft_convert_binary_to_octal.o ft_convert_decimal_to_binary.o ft_convert_decimal_to_hexadecimal.o ft_convert_decimal_to_octal.o ft_convert_hexa_to_binary.o ft_convert_hexa_to_decimal.o ft_convert_hexa_to_octal.o ft_convert_octal_to_binary.o ft_convert_octal_to_decimal.o ft_convert_octal_to_hexadecimal.o ft_strlen.o ft_strrev.o ft_swap.o ft_atoi.o ft_iterative_power.o ft_strcpy.o
	gcc -o main main.o ft_convert_base.o ft_strcmp.o ft_convert_binary_to_decimal.o ft_convert_binary_to_hexadecimal.o ft_convert_binary_to_octal.o ft_convert_decimal_to_binary.o ft_convert_decimal_to_hexadecimal.o ft_convert_decimal_to_octal.o ft_convert_hexa_to_binary.o ft_convert_hexa_to_decimal.o ft_convert_hexa_to_octal.o ft_convert_octal_to_binary.o ft_convert_octal_to_decimal.o ft_convert_octal_to_hexadecimal.o ft_strlen.o ft_strrev.o ft_swap.o ft_atoi.o ft_iterative_power.o ft_strcpy.o
main.o: main.c
	gcc -c main.c -o main.o
ft_convert_base.o: 
	gcc -c ft_convert_base.c -o ft_convert_base.o
ft_convert_binary_to_decimal.o: 
	gcc -c convert_binary/ft_convert_binary_to_decimal.c -o ft_convert_binary_to_decimal.o
ft_convert_binary_to_hexadecimal.o: 
	gcc -c convert_binary/ft_convert_binary_to_hexadecimal.c -o ft_convert_binary_to_hexadecimal.o
ft_convert_binary_to_octal.o: 
	gcc -c convert_binary/ft_convert_binary_to_octal.c -o ft_convert_binary_to_octal.o
ft_convert_decimal_to_binary.o: 
	gcc -c convert_decimal/ft_convert_decimal_to_binary.c -o ft_convert_decimal_to_binary.o
ft_convert_decimal_to_hexadecimal.o:
	gcc -c convert_decimal/ft_convert_decimal_to_hexadecimal.c -o ft_convert_decimal_to_hexadecimal.o
ft_convert_decimal_to_octal.o: 
	gcc -c convert_decimal/ft_convert_decimal_to_octal.c -o ft_convert_decimal_to_octal.o
ft_convert_hexa_to_binary.o: 
	gcc -c convert_hexadecimal/ft_convert_hexa_to_binary.c -o ft_convert_hexa_to_binary.o
ft_convert_hexa_to_decimal.o: 
	gcc -c convert_hexadecimal/ft_convert_hexa_to_decimal.c -o ft_convert_hexa_to_decimal.o
ft_convert_hexa_to_octal.o: 
	gcc -c convert_hexadecimal/ft_convert_hexa_to_octal.c -o ft_convert_hexa_to_octal.o
ft_convert_octal_to_binary.o: 
	gcc -c convert_octal/ft_convert_octal_to_binary.c -o ft_convert_octal_to_binary.o
ft_convert_octal_to_decimal.o: 
	gcc -c convert_octal/ft_convert_octal_to_decimal.c -o ft_convert_octal_to_decimal.o
ft_convert_octal_to_hexadecimal.o: 
	gcc -c convert_octal/ft_convert_octal_to_hexadecimal.c -o ft_convert_octal_to_hexadecimal.o
ft_strlen.o: 
	gcc -c ../../day03/ex06/ft_strlen.c -o ft_strlen.o
ft_strrev.o: 
	gcc -c ../../day03/ex07/ft_strrev.c -o ft_strrev.o
ft_swap.o: 
	gcc -c ../../day03/ex02/ft_swap.c -o ft_swap.o
ft_atoi.o: 
	gcc -c ../../day05/ex02/ft_atoi.c -o ft_atoi.o
ft_iterative_power.o: 
	gcc -c ../../day04/ex02/ft_iterative_power.c -o ft_iterative_power.o
ft_strcpy.o: 
	gcc -c ../../day05/ex03/ft_strcpy.c -o ft_strcpy.o
ft_strcmp.o: 
	gcc -c ../../day05/ex06/ft_strcmp.c -o ft_strcmp.o


clean : 
	rm *.o main 
